# Generated by Django 5.2.6 on 2025-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.CharField(help_text='URL pattern or route name', max_length=255, unique=True)),
                ('css_content', models.TextField(help_text='Critical CSS content to inline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Critical CSS',
                'verbose_name_plural': 'Critical CSS',
            },
        ),
    ]
