version: '3.8'

services:
  critical-css-service:
    build: .
    container_name: critical-css-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # Use host network for DNS resolution but explicit port mapping
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 208.67.222.222
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN  # Required for Chromium
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
